spring:
  quartz:
    job-store-type: jdbc
    auto-startup: true # Quartz 是否自动启动，集群模式下，如果需要某些机器不执行调度任务，可以配置成false
    startup-delay: 0   # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: false # 是否覆盖已有 Job 的配置
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
          scheduler:
            instanceId: AUTO
            instanceName: airisk

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/radar
    username: root
    password: 123555

#spring:
#  quartz:
#    job-store-type: jdbc #持久化到数据库
#    properties:
#      org:
#        quartz:
##          quartz的MySQL数据源配置
#          datasource:
#            # 新版驱动从com.mysql.jdbc.Driver变更为com.mysql.cj.jdbc.Driver
#            driver-class-name: com.mysql.cj.jdbc.Driver
#            # 数据源需要添加时间标准和指定编码格式解决乱码 You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
#            url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#            username: zzq
#            password: 123
#          scheduler:
#            instancName: clusteredScheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #StdJDBCDelegate说明支持集群
#            tablePrefix: QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 1000
#            useProperties: false
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 20
#            threadPriority: 5

logging:
  level:
    org.springframework.security: debug
    org.springframework.scheduling.quartz: debug
    org.hibernate.SQL: debug