server:
  port: 8080

spring:
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/ss?characterEncoding=utf-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
  #    username: root
  #    password: 123555
  thymeleaf:
    # 页面修改后立即生效，关闭缓存，立即刷新
    cache: false
  devtools:
    restart:
      enabled: true
      # 设置需要重启的目录
      additional-paths: src/java/main
      # 设置不需要重启的目录
      additional-exclude: static/**,public/**,WEB-INF/**

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
    secretKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALC2PKDTJ4FF8r+wTLeCRSbeLn7O/bO9cA98+huCKrJ+1HD5v3grXwqNa3Q/Jqn/5nI4LNirKrYq6YtkNhnSqAUCAwEAAQ==

logging:
  config: classpath:log4j2-dev.xml
  level:
    org.springframework.security: debug
